services:
  api:
    container_name: analytics-api
    build: .
    command: poetry run gunicorn src.wsgi:application
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:8000
    env_file:
      - ./src/.env
    environment:
      # for production
      - RENDER=1
